name: ${project.artifactId}
main: com.heroslender.herospawners.${project.artifactId}
version: ${project.version}
author: Heroslender
softdepend: [HolographicDisplays, MobStacker2, SilkSpawners, ObyStack, Multiverse-Core]
load: POSTWORLD

commands:
  herospawners:
    description: Main command
  spawners:
    description: give spawners command
    usage: "§cUso correto: §7/<command> <player> [entity] [stack size] [multiplier]"