name: ${project.artifactId}
main: com.heroslender.herospawners.${project.artifactId}
api-version: '1.13'
version: ${project.version}
author: Heroslender
softdepend: [HolographicDisplays, MobStacker2, SilkSpawners, ObyStack, Multiverse-Core, MultiWorld, StackMob]
load: POSTWORLD

commands:
  herospawners:
    description: Main command
  spawners:
    description: give spawners command
    usage: "§cUso correto: §7/<command> <player> [entity] [stack size] [multiplier]"

permissions:
  herospawners.admin:
    description: Admin permissions to the plugin
    default: op
    children:
      herospawners.break.others: true
  herospawners.break.others:
    description: Permission to break spawners the player does not own but is allowed by the region plugin.
    default: true